name: "Terraform-Develop"

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev


jobs:
  terraform:
    name: "Deploy-Development-Environment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: |
          export TF_WORKSPACE="sg"
          terraform init -input=false
          terraform workspace show
      

      - name: Terraform Plan
        id: plan
        run: |
          export TF_WORKSPACE="sg"
          terraform plan -input=false
        continue-on-error: true

